version: '3'

services:
  rasa_core:
    image: rasa/rasa_core:stable
    ports:
      - "8082:5005"
    volumes:
      - "./rasa-app-data/models/current/dialogue:/app/model"
      - "./rasa-app-data/config:/app/config"
      - "./rasa-app-data/project:/app/project"
    command: start -d ./model -u current/nlu --endpoints config/endpoints.yml --credentials config/credentials.yml
  action_server:
    build: ./rasa_core_sdk
    image: rasa_core_sdk:latest
    ports:
      - "8083:5055"
    volumes:
      - "./rasa-app-data/actions:/app/actions"
      - "./rasa-app-data/config:/app/config"
  rasa_nlu:
    image: rasa/rasa_nlu:stable-full
    ports:
      - "8084:5000"
    volumes:
      - "./rasa-app-data/models:/app/projects"
      - "./rasa-app-data/logs:/app/logs"
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8085:8000"
